build: fix uninitialized variables
Build for Fedora 34 is breaking out due to uninitialized variables in
 a few places:
 For example,
 [100%] Built target merger.test
/source/build/usr/src/debug/tarantool-2.9.0.116/src/box/sql.c: In function 'tarantoolSqlNextSeqId':
/source/build/usr/src/debug/tarantool-2.9.0.116/src/box/sql.c:1186:13: error: 'key' may be used uninitialized [-Werror=maybe-uninitialized]
 1186 |         if (box_index_max(BOX_SEQUENCE_ID, 0 /* PK */, key,

Needed for: #6074